<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
 xmlns:app="http://schemas.android.com/apk/res-auto"
 android:layout_width="match_parent"
 android:layout_height="fill_parent"
 android:orientation="vertical">
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:orientation="horizontal"
 android:weightSum="10">
 <ImageView
 android:id="@+id/register_btn_back"
 android:layout_width="wrap_content"
android:layout_height="match_parent"
 android:layout_weight="2"
 android:scaleType="fitXY"
 app:srcCompat="@drawable/register01_1"
 android:contentDescription="@string/StringValue"/>
 <ImageView
 android:id="@+id/register_imageView2"
 android:layout_width="wrap_content"
 android:layout_height="37dp"
 android:layout_weight="8"
 android:scaleType="fitXY"
 app:srcCompat="@drawable/register01_2"
 android:contentDescription="@string/StringValue"/>
 </LinearLayout>
 <ImageView
 android:id="@+id/register_imageView3"
 android:layout_width="match_parent"
 android:layout_height="67dp"
 android:scaleType="fitXY"
 app:srcCompat="@drawable/register02"
 android:contentDescription="@string/StringValue" />
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:layout_marginLeft="20dp"
 android:layout_marginTop="10dp"
 android:layout_marginRight="20dp"
 android:orientation="horizontal">
 <EditText
 android:id="@+id/register_et_id"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_id"
 android:importantForAutofill="no"
 android:background="@drawable/register03"
 android:textSize="12sp"
 android:inputType="textPersonName"
 android:paddingStart="10dp"
 android:paddingLeft="10dp"
 android:paddingEnd="0dp"
 android:paddingRight="0dp"/>
 </LinearLayout>
 <LinearLayout
 android:layout_width="match_parent"
  android:layout_height="wrap_content"
 android:layout_marginLeft="20dp"
 android:layout_marginTop="15dp"
 android:layout_marginRight="20dp"
 android:orientation="horizontal">
 <EditText
 android:id="@+id/register_et_pw"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_pw"
 android:importantForAutofill="no"
 android:textSize="12sp"
 android:background="@drawable/register03"
 android:inputType="textPersonName"
 android:paddingStart="10dp"
 android:paddingLeft="10dp"
 android:paddingEnd="0dp"
 android:paddingRight="0dp" />
 </LinearLayout>
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:layout_marginLeft="20dp"
 android:layout_marginTop="15dp"
 android:layout_marginRight="20dp"
 android:orientation="horizontal">
 <EditText
 android:id="@+id/register_et_pwcheck"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_pwcheck"
 android:importantForAutofill="no"
 android:textSize="12sp"
 android:background="@drawable/register03"
 android:inputType="textPersonName"
 android:paddingStart="10dp"
 android:paddingLeft="10dp"
 android:paddingEnd="0dp"
 android:paddingRight="0dp" />
 </LinearLayout>
 <ImageView
 android:id="@+id/register_imageView4"
 android:layout_width="57dp"
 android:layout_height="24dp"
  android:layout_marginLeft="20dp"
 android:layout_marginTop="120dp"
 app:srcCompat="@drawable/register04"
 android:contentDescription="@string/StringValue"
 android:layout_marginStart="20dp" />
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:layout_marginLeft="20dp"
 android:layout_marginTop="10dp"
 android:layout_marginRight="20dp"
 android:orientation="horizontal">
 <EditText
 android:id="@+id/register_et_name"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_id"
 android:importantForAutofill="no"
 android:textSize="12sp"
 android:background="@drawable/register03"
 android:inputType="textPersonName"
 android:paddingStart="10dp"
 android:paddingLeft="10dp"
 android:paddingEnd="0dp"
 android:paddingRight="0dp" />
 </LinearLayout>
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:layout_marginLeft="20dp"
 android:layout_marginTop="15dp"
 android:layout_marginRight="20dp"
 android:orientation="horizontal">
 <EditText
 android:id="@+id/register_et_age"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_pw"
 android:importantForAutofill="no"
 android:textSize="12sp"
 android:background="@drawable/register03"
 android:inputType="textPersonName"
 android:paddingStart="10dp"
 android:paddingLeft="10dp"
android:paddingEnd="0dp"
 android:paddingRight="0dp" />
 </LinearLayout>
 <LinearLayout
 android:layout_width="match_parent"
 android:layout_height="match_parent"
 android:orientation="horizontal">
 <ImageView
 android:id="@+id/register_btn_register"
 android:layout_width="match_parent"
 android:layout_height="60dp"
 android:layout_marginLeft="10dp"
 android:layout_marginTop="80dp"
 android:layout_marginRight="10dp"
 android:scaleType="fitXY"
 android:contentDescription="@string/StringValue"
 app:srcCompat="@drawable/register05" />
 </LinearLayout>
</LinearLayout>
